[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dax-web"
version = "0.1.0"
authors = [
  { name = "LORD-SANTINO", email = "mikkyrose297@gmail.com" }
]
description = "A short description of your project"
requires-python = ">=3.8"
